# syntax=docker/dockerfile:1
FROM arm64v8/ros:humble AS main-setup

# opencv 4.x cpp compilation

#RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
#RUN wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.x.zip

#RUN unzip opencv.zip
#RUN unzip opencv_contrib.zip

#RUN mkdir -p opencv/build && cd opencv/build
#RUN cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.x/modules ../opencv-4.x
#RUN cmake --build .
#RUN make install

RUN useradd -rm -d /home/sky -s /bin/bash -g root -G sudo -u 1000 sky -p "$(openssl caio123 -1 sky)"
USER sky
WORKDIR /home/sky

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

RUN sudo apt update && sudo apt upgrade -y

RUN sudo apt-get install ros-humble-mavros ros-humble-mavros-extras -y 
RUN wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
RUN chmod a+x install_geographiclib_datasets.sh
RUN sudo ./install_geographiclib_datasets.sh

RUN . ~/.profile
RUN pip3 install mavproxy
