# syntax=docker/dockerfile:1
FROM osrf/ros:humble-simulation AS main-setup

ENV DISPLAY=:0
ENV XDG_RUNTIME_DIR=/tmp/runtime-root

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \ 
    lsb-release \ 
    gnupg 

# Install Gazebo
RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update && apt-get install -y \
    gz-harmonic 